/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokusolverfinal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
//import java.awt.Toolkit;
import javax.swing.BorderFactory;
//import javax.swing.JLabel;
import javax.swing.JTextField;
//import javax.swing.text.AttributeSet;
//import javax.swing.text.BadLocationException;
//import javax.swing.text.PlainDocument;

/**
 *
 * @author Brian Spann (rbs4ba) & Jessica Ya (jy2fv), Final Theory Project
 * based off of Nicholas Dunn's grid
 */

/** TODO:
 * XInstead of inputting numbers, display number from a 2D array
 * Display colors for nonominos
 * 
 */
public class Squares extends javax.swing.JPanel {

    //private JTextField nw, n, ne, e, c, w, sw, s, se;
    private JTextField[] txtFields;// = new JTextField[]{
        //nw, n, ne, e, c, w, sw, s, se
    //};

    private static final int BORDER_WIDTH = 2;
    /**
     * Creates new form Squares
     * @param background
     * @param s
     */
    public Squares(Color background, int s) { //int s is the sqrt(n)
        
        txtFields = new JTextField[(int) Math.pow((double) s, 2)];

        setLayout(new GridLayout(s, s));
        initGUI((int) Math.pow((double) s, 2));
        setBackground(background);
    }

    private void initGUI(int n) {
        
        for (int i = 0; i < n; i++) {//for (int i = 0; i < txtFields.length; i++) {
        txtFields[i] = new JTextField(2);//(1); //changed to 2 to accept bigger #s
        txtFields[i].setText(" ");
        //txtFields[i].setBackground(Color.MAGENTA);
        //txtFields[i].setDocument(new NumericalDocument()); //extends PlainDocument
        txtFields[i].setEditable(false);
        add(txtFields[i]);  
    }
        setBorder(BorderFactory.createMatteBorder(BORDER_WIDTH,BORDER_WIDTH,BORDER_WIDTH,BORDER_WIDTH, Color.CYAN));
    }
    
    public Dimension getPrefDimension() {
        return new Dimension(100, 100); //try changing dimensions
    }
    /**
    public JTextField getJTextField(int index) {
        return txtFields[index];
    }
    */
    public JTextField[] getJTextField() {
        return txtFields;
    }
    /**
    public static class NumericalDocument extends PlainDocument {
        String numbers = "0123456789"; //0 necessary?
        @Override
        public void insertString(int offset, String s, AttributeSet a) throws BadLocationException {
            if (getLength() == 0 && s.length() == 1 && numbers.contains(s)) {
                super.insertString(offset, s, a);
            }
            else {
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
