/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokusolverfinal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Brian Spann (rbs4ba) & Jessica Ya (jy2fv), Final Theory Project
 * based off of Nicholas Dunn's grid
 */
public class Squares extends javax.swing.JPanel {

    private JTextField nw, n, ne, e, c, w, sw, s, se;
    private JTextField[] txtFields = new JTextField[]{
        nw, n, ne, e, c, w, sw, s, se
    };
    
    private static final int BORDER_WIDTH = 2;
    /**
     * Creates new form Squares
     */
    public Squares(Color background) {
        setLayout(new GridLayout(3, 3));
        initGUI();
        setBackground(background);
    }

    private void initGUI() {
        for (int i = 0; i < txtFields.length; i++) {
        txtFields[i] = new JTextField(1);
        txtFields[i].setDocument(new NumericalDocument()); //extends PlainDocument
        add(txtFields[i]);  
    }
        setBorder(BorderFactory.createMatteBorder(BORDER_WIDTH,BORDER_WIDTH,BORDER_WIDTH,BORDER_WIDTH, Color.CYAN));
    }
    
    public Dimension getPrefDimension() {
        return new Dimension(100, 100); //try changing dimensions
    }
    
    public static class NumericalDocument extends PlainDocument {
        String numbers = "0123456789"; //0 necessary?
        @Override
        public void insertString(int offs, String s, AttributeSet a) throws BadLocationException {
            if (getLength() == 0 && s.length() == 1 && numbers.contains(s)) {
                super.insertString(offs, s, a);
            }
            else {
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
